; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0607091B-1085-4D55-B269-F96A8C98D8CF}
AppName=Delfinovin
AppVersion=3.0
AppVerName=Delfinovin 3.0
AppPublisher=Struggleton
AppPublisherURL=https://github.com/Struggleton/Delfinovin
AppSupportURL=https://github.com/Struggleton/Delfinovin
AppUpdatesURL=https://github.com/Struggleton/Delfinovin
DefaultDirName={autopf32}\Delfinovin
DisableDirPage=yes
UninstallDisplayIcon={app}\Delfinovin.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x86compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x86compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=.\
OutputBaseFilename=DelfinovinSetup
SetupIconFile=..\Resources\Icons\app.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\bin\Release\net7.0-windows\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Delfinovin"; Filename: "{app}\Delfinovin.exe"
Name: "{autodesktop}\Delfinovin"; Filename: "{app}\Delfinovin.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Delfinovin.exe"; Description: "{cm:LaunchProgram,Delfinovin}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{userdocs}\Delfinovin\profiles"
Type: filesandordirs; Name: "{userdocs}\Delfinovin\recordings"
Type: filesandordirs; Name: "{userdocs}\Delfinovin"